modLoader="javafml"
loaderVersion="[37,)"
issueTrackerURL="https://github.com/EdwinMindcraft/calio/issues" #optional
license="MIT"

[[mods]]
modId="calio"
version="${version}"
displayName="Calio"
logoFile= "calio_icon.png"
authors="apace100"
description='''
A simple library mod, mainly adds a serializable data system.
'''

[[dependencies.calio]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.74,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.calio]]
    modId="minecraft"
    mandatory=true
    versionRange="[${mc_version}]"
    ordering="NONE"
    side="BOTH"